version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.0.0
    steps:
      - checkout
      - run:   
          name: Install npm packages
          command: |
            npm install
      - run:
          name: Update npm
          command: |
            npm run migrate